package it.restservice.gym.fitnesspoint.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import it.restservice.gym.fitnesspoint.utils.Utils;

@JsonInclude(Include.NON_NULL)
@DynamoDBTable(tableName = "news")
public class News {

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute(attributeName = "title")
	private String title;
	
	@DynamoDBAttribute(attributeName = "description")
	private String description;
	
	@DynamoDBAttribute(attributeName = "date")
	private Long date;
	
	@DynamoDBAttribute(attributeName = "img")
	private String image;
	
	@DynamoDBAttribute(attributeName = "url")
	private String url;
	
	@DynamoDBAttribute(attributeName = "dat_ins")
	private Long dateIns;
	
	@DynamoDBAttribute(attributeName = "showed")
	@DynamoDBTyped(DynamoDBAttributeType.BOOL)
	private boolean showed;
	
	public News() {}
	
	public News(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}

	public Long getDate() {
		return date;
	}
	public void setDate(Long date) {
		this.date = date;
	}

	public String getImage() {
		return image;
	}
	public void setImage(String image) {
		this.image = image;
	}

	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}

	public Long getDateIns() {
		return dateIns;
	}
	public void setDateIns(Long dateIns) {
		this.dateIns = dateIns;
	}

	public boolean isShowed() {
		return showed;
	}
	public void setShowed(boolean showed) {
		this.showed = showed;
	}
	
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("News {");
		sb.append("id: " + id);
		sb.append(", title: " + title);
		sb.append(", description:" + description);
		sb.append(", date:" + Utils.formatDate(date, Utils.DATE_FORMAT_SHORT));
		sb.append(", image:" + image);
		sb.append(", url:" + url);
		sb.append(", showed:" + showed);
		sb.append(", dateIns:" + Utils.formatDate(dateIns, Utils.DATE_FORMAT_FULL));
		sb.append("}");  
		return sb.toString();
	}
}
